ARG BUILD_FROM
FROM $BUILD_FROM

ENV LANG C.UTF-8


RUN mkdir /device_tracker
WORKDIR /device_tracker

#RUN wget https://github.com/Smekl/Device-Tracker/archive/refs/tags/0.5.tar.gz
#RUN tar xzf 0.5.tar.gz --strip-components=1
#RUN apk add --no-cache python3 py-pip libpcap
#RUN pip install scapy requests
#RUN chmod +x hotfixes/scapy.sh && ./hotfixes/scapy.sh
#RUN chmod +x ./run.sh
#CMD [ "./run.sh" ]
